#define NICK_LEN 128
#define INFOS_LEN 128

enum msg_type {
	NICKNAME_NEW,
	NICKNAME_LIST,
	NICKNAME_INFOS,
	ECHO_SEND,
	UNICAST_SEND,
	BROADCAST_SEND,
	MULTICAST_CREATE,
	MULTICAST_LIST,
	MULTICAST_JOIN,
	MULTICAST_SEND,
	MULTICAST_QUIT,
	FILE_REQUEST,
	FILE_ACCEPT,
	FILE_REJECT,
	FILE_SEND,
	FILE_ACK,
	WELCOME,
	QUIT,
	ERROR_LOGIN,
	ERROR_COMMAND,
	ERROR_MULTICAST_CREATE,
	QUIT_CHANNEL,
	ERROR_QUIT_CHANNEL,
	ERROR_MULTICAST_JOIN,
	SERVER,
	COLOR,
	MAN_COLOR
};

struct message {
	int pld_len;
	char nick_sender[NICK_LEN];
	enum msg_type type;
	char infos[INFOS_LEN];
};

static char* msg_type_str[] = {
	"NICKNAME_NEW",
	"NICKNAME_LIST",
	"NICKNAME_INFOS",
	"ECHO_SEND",
	"UNICAST_SEND",
	"BROADCAST_SEND",
	"MULTICAST_CREATE",
	"MULTICAST_LIST",
	"MULTICAST_JOIN",
	"MULTICAST_SEND",
	"MULTICAST_QUIT",
	"FILE_REQUEST",
	"FILE_ACCEPT",
	"FILE_REJECT",
	"FILE_SEND",
	"FILE_ACK",
	"WELCOME",
	"QUIT",
	"ERROR_LOGIN",
	"ERROR_COMMAND",
	"ERROR_MULTICAST_CREATE",
	"QUIT_CHANNEL",
	"ERROR_QUIT_CHANNEL",
	"ERROR_MULTICAST_JOIN",
	"SERVER",
	"COLOR",
	"MAN_COLOR"
};
